branches: 
  - main
debug: false
dryRun: false
ci: true
tagFormat: v${version}
plugins:
  - "@semantic-release/git"
verifyConditions:
  - '@semantic-release/git'
  - "@semantic-release/github"
analyzeCommits:
  - path: "@semantic-release/commit-analyzer"
    releaseRules:
    - type: "feat"
      release: "minor"
    - type: "hotfix"
      release: "patch"
    - type: "patch"
      release: "patch"
    - type: "minor"
      release: "minor"
    - type: "breaking"
      release: "major"
    - type: "refactor"
      release: "major"
generateNotes:
  - path: "@semantic-release/release-notes-generator"
    writerOpts:
      groupBy: "type"
      commitGroupsSort:
        - "breaking"
        - "feat"
        - "perf"
        - "fix"
      commitsSort: "header"
    types:
    # Tracked major breaking changes
    - type: "breaking"
    - section: "Major Version"
    # Tracked Features
    - type: "feat"
    - section: "Features"
    # Tracked bug fix with a hotfix branch
    - type: "hotfix"
    - section: "Bug Fixes"
    - type: "fix"
    - section: "Bug Fixes"
    # Uninmportent fix (CI testing, etc)
    - type: "chore"
    - hidden: true
    - type: "docs"
    - hidden: true
    - type: "doc"
    - hidden: true
    - type: "style"
    - hidden: true
    - type: "refactor"
    - hidden: true
    - type: "perf"
    - hidden: true
    - type: "test"
    - hidden: true
    presetConfig: true
prepare:
  - path: "@semantic-release/changelog"
    changelogFile: "CHANGELOG.md"
  - path: "@semantic-release/git"
    message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
    assets:
      - CHANGELOG.md
publish:
  - path: "@semantic-release/github"

success:
  - "@semantic-release/github"

fail:
  - "@semantic-release/github"
